version: '2'

services:
  card-broker:
    image: mhhoban/dukedoms-mock-card-broker:latest
    ports:
      - 5006:8080

  db:
    image: mhhoban/dukedoms-rdbs
    environment:
      POSTGRES_PASSWORD: daleria
    ports:
      - 5432:5432
